language: julia

os:
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: 1.0
    - julia: 1.1
    - julia: 1.2
    - julia: 1.4
    - julia: nightly


notifications:
  email:
    recipients: varga.andreas@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master

#codecov: true

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MatrixPencils")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: windows
      script:
        - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Documenter"))' && julia docs/make.jl
      after_success: skip

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.2
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip